import type { Product, Customer, Transaction, DeliveryLocation, SalesOrder } from "@/types/pos"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Coffee - Medium",
    price: 3.5,
    category: "Beverages",
    stock: 100,
    barcode: "123456789012",
    image: "/coffee-cup-medium-roast.png",
  },
  {
    id: "2",
    name: "Croissant",
    price: 2.75,
    category: "Bakery",
    stock: 25,
    barcode: "123456789013",
    image: "/fresh-golden-croissant-pastry.png",
  },
  {
    id: "3",
    name: "Sandwich - Turkey",
    price: 8.99,
    category: "Food",
    stock: 15,
    barcode: "123456789014",
    image: "/turkey-sandwich-with-lettuce-tomato.png",
  },
  {
    id: "4",
    name: "Water Bottle",
    price: 1.99,
    category: "Beverages",
    stock: 50,
    barcode: "123456789015",
    image: "/clear-plastic-water-bottle.png",
  },
  {
    id: "5",
    name: "Muffin - Blueberry",
    price: 3.25,
    category: "Bakery",
    stock: 20,
    barcode: "123456789016",
    image: "/blueberry-muffin-with-berries.png",
  },
  {
    id: "6",
    name: "Espresso",
    price: 2.25,
    category: "Beverages",
    stock: 75,
    barcode: "123456789017",
    image: "/espresso-shot.png",
  },
  {
    id: "7",
    name: "Bagel - Everything",
    price: 2.5,
    category: "Bakery",
    stock: 30,
    barcode: "123456789018",
    image: "/everything-bagel-with-seeds.png",
  },
  {
    id: "8",
    name: "Salad - Caesar",
    price: 9.99,
    category: "Food",
    stock: 12,
    barcode: "123456789019",
    image: "/caesar-salad-with-croutons-parmesan.png",
  },
  {
    id: "9",
    name: "Orange Juice",
    price: 3.75,
    category: "Beverages",
    stock: 35,
    barcode: "123456789020",
    image: "/fresh-orange-juice.png",
  },
  {
    id: "10",
    name: "Chocolate Chip Cookie",
    price: 1.75,
    category: "Bakery",
    stock: 45,
    barcode: "123456789021",
    image: "/chocolate-chip-cookie-golden-brown.png",
  },
]

export const mockCustomers: Customer[] = [
  {
    id: "1",
    customerCode: "CUST001",
    name: "John Doe",
    email: "john@example.com",
    phone: "555-0123",
    address: "123 Main St, City, State 12345",
    creditLimit: 5000,
    paymentTerms: "NET30",
    isActive: true,
    totalPurchases: 145.67,
    defaultDeliveryLocationId: "1",
  },
  {
    id: "2",
    customerCode: "CUST002",
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "555-0124",
    address: "456 Oak Ave, City, State 12345",
    creditLimit: 3000,
    paymentTerms: "NET15",
    isActive: true,
    totalPurchases: 89.32,
    defaultDeliveryLocationId: "2",
  },
  {
    id: "3",
    customerCode: "CUST003",
    name: "Acme Corporation",
    email: "orders@acme.com",
    phone: "555-0125",
    address: "789 Business Blvd, City, State 12345",
    creditLimit: 10000,
    paymentTerms: "NET45",
    isActive: true,
    totalPurchases: 2456.78,
    defaultDeliveryLocationId: "3",
  },
]

export const mockDeliveryLocations: DeliveryLocation[] = [
  {
    id: "1",
    code: "MAIN",
    name: "Site Principal",
    address: "123 Main St, City, State 12345",
    contactPerson: "John Doe",
    contactPhone: "555-0123",
    isActive: true,
    isDefault: true,
  },
  {
    id: "2",
    code: "WEST",
    name: "Entrepôt Ouest",
    address: "456 Oak Ave, City, State 12345",
    contactPerson: "Jane Smith",
    contactPhone: "555-0124",
    isActive: true,
    isDefault: false,
  },
  {
    id: "3",
    code: "CORP",
    name: "Siège Social Acme",
    address: "789 Business Blvd, City, State 12345",
    contactPerson: "Bob Johnson",
    contactPhone: "555-0125",
    isActive: true,
    isDefault: false,
  },
  {
    id: "4",
    code: "EAST",
    name: "Dépôt Est",
    address: "321 Industrial Way, City, State 12345",
    contactPerson: "Sarah Wilson",
    contactPhone: "555-0126",
    isActive: true,
    isDefault: false,
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    items: [
      {
        productId: "1",
        product: mockProducts[0],
        quantity: 2,
        unitPrice: 3.5,
        totalPrice: 7.0,
      },
    ],
    subtotal: 7.0,
    tax: 0.56,
    total: 7.56,
    paymentMethod: "card",
    customerId: "1",
    customer: mockCustomers[0],
    timestamp: new Date(),
    status: "completed",
  },
]

export const mockSalesOrders: SalesOrder[] = [
  {
    id: "order-1",
    orderNumber: "SOH-20241203-0001",
    customerId: "1",
    customer: mockCustomers[0],
    deliveryLocationId: "1",
    deliveryLocation: mockDeliveryLocations[0],
    items: [
      {
        id: "item-1",
        productId: "1",
        product: mockProducts[0],
        quantity: 10,
        unitPrice: 3.5,
        discount: 0,
        totalPrice: 35.0,
        reservedStock: 10,
      },
      {
        id: "item-2",
        productId: "2",
        product: mockProducts[1],
        quantity: 5,
        unitPrice: 2.75,
        discount: 0,
        totalPrice: 13.75,
        reservedStock: 5,
      },
    ],
    subtotal: 48.75,
    tax: 3.9,
    discount: 0,
    total: 52.65,
    status: "confirmed",
    createdAt: new Date(Date.now() - 86400000), // Yesterday
    updatedAt: new Date(Date.now() - 86400000),
    createdBy: "user1",
    approvedBy: "manager1",
    approvedAt: new Date(Date.now() - 82800000),
    priority: "normal",
    expectedDeliveryDate: new Date(Date.now() + 172800000), // In 2 days
    modifications: [
      {
        id: "mod-1",
        timestamp: new Date(Date.now() - 86400000),
        userId: "user1",
        action: "created",
        reason: "Commande créée",
      },
      {
        id: "mod-2",
        timestamp: new Date(Date.now() - 82800000),
        userId: "manager1",
        action: "approved",
        reason: "Commande approuvée",
      },
    ],
  },
]
